output_from_input_dict:
  template_1.xlsx: # Excel to copy to the outputs folder and add all the data to it
    tables: # Specify the tables in the Excel that you want to add data to
      Table1_customer_list:
        customer_data.csv:
          column_mapping:
            First: "First Name"
            Last: "Last Name"
            Start: "Start_date"
            Sales: "Purchases"
          column_types:
            First: text
            Start: date
            Sales: float
      Table2_customer_list:
        customer_data2.csv:
          column_mapping:
            First: "First Name"
            Last: "Last Name"
            Start: "Start_date"
            Sales: "Purchases"
          column_types:
            First: text
            Start: date
            Sales: float
      Table2_customer_list2:
        customer_data2.xlsx:
          xl_table:
            name: "table1"
            column_mapping:
              First: "First Name"
              Last: "Last Name"
              Start: "Start_date"
              Sales: "Purchases"
            column_types:
              First: text
              Start: date
              Sales: float
      Table2_customer_list3:
        customer_data2.xlsx:
          xl_sheet:
            name: "sheet1"
            column_mapping:
              First: "First Name"
              Last: "Last Name"
              Start: "Start_date"
              Sales: "Purchases"
            column_types:
              First: text
              Start: date
              Sales: float
      Table3_customer_list:
        customer_data3.csv:
          column_mapping:
            First: "First Name"
            Last: "Last Name"
            Start: "Start_date"
            Sales: "Purchases"
          column_types:
            First: text
            Start: date
            Sales: float
    sheets: # Specify the sheets in the Excel that you want to directly add data to
      # Note: Any data already existing in this sheet will be removed
      sheet_name: # This is the sheet you want to add data to
        customer_data.csv: # You want to add the data from 'customer_data.csv' to that sheet
          column_mapping: # Detail any renaming of column names from teh source data
            First: "First Name"
            Last: "Last Name"
            Start: "Start_date"
            Sales: "Purchases"
          column_types: # Specify any data types for the data to be loaded
            First: string
            Start: date
            Sales: float64
